export const TRANSLATE_LOCATION_PENDING = 'TRANSLATE_LOCATION_PENDING';
export const TRANSLATE_LOCATION_SUCCESS = 'TRANSLATE_LOCATION_SUCCESS';
export const TRANSLATE_LOCATION_FAILED = 'TRANSLATE_LOCATION_FAILED';

export const GET_LATLONG_PENDING = 'GET_LATLONG_PENDING';
export const GET_LATLONG_SUCCESS = 'GET_LATLONG_SUCCESS';
export const GET_LATLONG_FAILED = 'GET_LATLONG_FAILED';

export const WEATHER_FINDER_PENDING = 'WEATHER_FINDER_PENDING';
export const WEATHER_FINDER_SUCCESS = 'WEATHER_FINDER_SUCCESS';
export const WEATHER_FINDER_FAILED = 'WEATHER_FINDER_FAILED';

export const LOCATE_USER_PENDING = 'LOCATE_USER_PENDING';
export const LOCATE_USER_SUCCESS = 'LOCATE_USER_SUCCESS';
export const LOCATE_USER_FAILED = 'LOCATE_USER_FAILED';


export const corsProxy = "https://cors-anywhere.herokuapp.com/";
export const CHANGE_ZIPCODE = 'CHANGE_ZIPCODE';
export const GET_DATE = 'GET_DATE';
export const FOCUS_CARD = 'FOCUS_CARD';