export const TRANSLATE_LOCATION_PENDING = 'TRANSLATE_LOCATION_PENDING';
export const TRANSLATE_LOCATION_SUCCESS = 'TRANSLATE_LOCATION_SUCCESS';
export const TRANSLATE_LOCATION_FAILED = 'TRANSLATE_LOCATION_FAILED';