export const TRANSLATE_LOCATION_PENDING = 'TRANSLATE_LOCATION_PENDING';
export const TRANSLATE_LOCATION_SUCCESS = 'TRANSLATE_LOCATION_SUCCESS';
export const TRANSLATE_LOCATION_FAILED = 'TRANSLATE_LOCATION_FAILED';

export const WEATHER_FINDER_PENDING = 'WEATHER_FINDER_PENDING';
export const WEATHER_FINDER_SUCCESS = 'WEATHER_FINDER_SUCCESS';
export const WEATHER_FINDER_FAILED = 'WEATHER_FINDER_FAILED';
export const corsProxy = "https://cors-anywhere.herokuapp.com/";
